# -*- coding: utf-8 -*-
"""big data lab 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E_jRTqZj7fMmgj7KLRyFHAAXAbLJesr7
"""

import numpy as np

ini_array = np.array([1, 2, 3, 6, 4, 5])
res = np.flip(ini_array)
print("final array", str(res))

import numpy as np

an_array = np.array([[1, 2], [3, 4]])
another_array = np.array([[1, 2], [3, 4]])

comparison = an_array == another_array
equal_arrays = comparison.all()

print(equal_arrays)

import numpy as np

arr = np.array([1,2,2,3,4,3,5,5,5])
print("Original array:")
print(arr)

print("Most frequent value in the above array:")
print(np.bincount(arr).argmax())

import numpy as np


arr = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')


total_sum = np.sum(arr)


row_sum = np.sum(arr, axis=1)

col_sum = np.sum(arr, axis=0)

print("Matrix:")
print(arr)

print("\ni. Sum of all elements:", total_sum)

print("\nii. Sum of all elements row-wise:")
print(row_sum)

print("\niii. Sum of all elements column-wise:")
print(col_sum)